export const tutorial = {
    section_1: "Welcome aboard! This is SuitsUp!, a turn-based multiplayer game in which you win by simply matching suits with the topmost card on the foundation.\nThe game uses a deck of 52 playing cards which are distributed on the piles. There are three kinds of piles: Player piles on the ends of the table, Foundation pile at the centre of the table and Market pile at the Top section of the screen.\n\n\n\n",
    section_2: "This is the top section, where we have the Market and Scoreboard. Tap the Clock icon to toggle (on/off) the stopwatch sound. The About section brings you here - to the tutorial menu.\n\n\n\n",
    section_3: "This is the table, which accomodates 2 - 4 players. At the start of the game, each participant is dealt 10 cards. The remaining cards are kept in the market.\nThe game starts with you clicking on your card pile. All the remaining participants then deal in a clockwise fashion. Dealing continues until a participant wins the round.\n\nWhen a participant runs out of card, a new card is automatically purchased from the market at the cost of 1 point (That is, 1 point is automatically deducted from the player's current score).\n\n\n\n",
    section_4: "Here is the bottom section where Live commentaries are displayed.\n\n\n\n",
    section_5: "A round is won if the last player to deal has dealt a suit that matches the topmost suit on the foundation.\n\n\n\n",
    section_6: "When the next player to deal has no cards left and there are no cards left in the market to purchase, the participant who won the previous round deals 3 times consecutively. If s(he) wins while dealing, the game ends. Otherwise, all the foundation piles are sent to the market.\n\n\n\n",
    section_7: "The winner of a round gets a point for each card obtained from the Foundation. A participant that takes a card from the market loses a point for each card taken.\n\n\n\n",
    section_8: "There are five difficulty levels: Easy, Normal, Hard, Legend and Hell. The logic behind the levels is that you more favourable hands when it's your turn to deal. Easy Mode gives you 85% chance of winning the round, while Hell Mode is... well, hellish.\n\n\n\n",
    section_9: "There are 3 Game Modes: Classic, Race Against Time, and First To 70.\nClassic: Here, the game is played until only one player remains.\nRace Against Time: In this mode, player specifies for how long (in minutes) they want to the game to continue. Once the time lapses, whoever has the highest score is declared winner, provided that nobody wins in a classic fashion before that.\nFirst To 70: This game mode runs for as long as it takes one of the participants to reach a score of 70, provided that nobody wins in a classic fashion before then.\n\n\n\n",
    section_10: "We hope you enjoy playing the game. Have fun!!\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n", 
};